// data.tsx or constants.tsx

import type { Category, Stat } from "./types"; // optional if using types separately

export const allCategories: Category[] = [
  {
    name: "Air Conditioner",
    mainCategory: "Domestic Appliance",
    type: "Cooling",
    image: "air_conditioner",
    description: "Professional Split AC services including installation, repair, and maintenance",
  },
  {
    name: "Cassette AC",
    mainCategory: "Domestic Appliance",
    type: "Cooling",
    image: "cassette_ac",
    description: "Ceiling mounted air conditioning units for commercial spaces",
  },
  {
    name: "Deep Freezer",
    mainCategory: "Retail",
    type: "Cooling",
    image: "deep_freezer",
    description: "Commercial and industrial freezing solutions",
  },
  {
    name: "Visi Cooler",
    mainCategory: "Retail",
    type: "Cooling",
    image: "visi_cooler",
    description: "Display coolers for beverages and retail spaces",
  },
  {
    name: "Display Counter",
    mainCategory: "Retail",
    type: "Display",
    image: "display_counter",
    description: "Attractive display counters for showcasing products",
  },
  {
    name: "Geyser",
    mainCategory: "Domestic Appliance",
    type: "Heating",
    image: "geyser",
    description: "Comprehensive geyser repair and installation services",
  },
  {
    name: "Food Prep Chiller",
    mainCategory: "Kitchen",
    type: "Cooling",
    image: "food_prep_chiller",
    description: "Chilling solutions for food preparation and storage",
  },
  {
    name: "Back Bar Chiller",
    mainCategory: "Kitchen",
    type: "Cooling",
    image: "back_bar_chiller",
    description: "Bar and beverage cooling solutions for commercial use",
  },
  {
    name: "Ice Maker",
    mainCategory: "Kitchen",
    type: "Cooling",
    image: "ice_maker",
    description: "Commercial ice making machines for businesses",
  },
  {
    name: "Upright Chiller",
    mainCategory: "Kitchen",
    type: "Cooling",
    image: "upright_chiller",
    description: "Vertical cooling solutions for commercial spaces",
  },
  {
    name: "Water Purifier",
    mainCategory: "Domestic Appliance",
    type: "Water",
    image: "water_purifier",
    description: "Expert water purifier installation and maintenance services",
  },
  {
    name: "Washing Machine",
    mainCategory: "Domestic Appliance",
    type: "Cleaning",
    image: "washing_machine",
    description: "Expert washing machine repair and maintenance services",
  },
  {
    name: "Refrigerator",
    mainCategory: "Domestic Appliance",
    type: "Cooling",
    image: "refrigerator",
    description: "Professional refrigerator repair and maintenance services",
  },
  {
    name: "Air Purifier",
    mainCategory: "Domestic Appliance",
    type: "Air Quality",
    image: "air_purifier",
    description: "Clean air solutions for your space",
  },
  {
    name: "Microwave",
    mainCategory: "Kitchen",
    type: "Cooking",
    image: "microwave",
    description: "Expert microwave repair and maintenance services",
  },
  {
    name: "Water Dispenser",
    mainCategory: "Retail",
    type: "Water",
    image: "water_dispenser",
    description: "Hot and cold water dispensing solutions",
  },
  {
    name: "Water Cooler cum Purifier",
    mainCategory: "Domestic Appliance",
    type: "Water",
    image: "water_cooler_cum_purifier",
    description: "Dual-function water cooler and purifier",
  },
  {
    name: "Air Cooler",
    mainCategory: "Domestic Appliance",
    type: "Cooling",
    image: "air_cooler",
    description: "Energy efficient cooling solutions",
  },
];

export const categoryImageMap: Record<string, any> = {
  air_conditioner: require("@/assets/air_conditioner.jpeg"),
  cassette_ac: require("@/assets/cassette_ac.jpeg"),
  deep_freezer: require("@/assets/deep_freezer.jpeg"),
  visi_cooler: require("@/assets/visi_cooler.jpeg"),
  display_counter: require("@/assets/display_counter.jpeg"),
  geyser: require("@/assets/geyser.jpeg"),
  food_prep_chiller: require("@/assets/food_prep_chiller.jpeg"),
  back_bar_chiller: require("@/assets/back_bar_chiller.jpeg"),
  ice_maker: require("@/assets/ice_maker.jpeg"),
  upright_chiller: require("@/assets/upright_chiller.jpeg"),
  water_purifier: require("@/assets/water_purifier.jpeg"),
  washing_machine: require("@/assets/washing_machine.jpeg"),
  refrigerator: require("@/assets/refrigerator.jpeg"),
  air_purifier: require("@/assets/air_purifier.jpeg"),
  microwave: require("@/assets/microwave.jpeg"),
  water_dispenser: require("@/assets/water_dispenser.jpeg"),
  water_cooler_cum_purifier: require("@/assets/water_cooler.jpeg"),
  air_cooler: require("@/assets/air_cooler.jpeg"),
};

export const stats: Stat[] = [
  {
    end: 15,
    text: "Years Experience",
    color: "blue",
    icon: "M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806...",
  },
  {
    end: 1531,
    text: "Happy Customers",
    color: "green",
    icon: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7...",
  },
  {
    end: 37,
    text: "Expert Technicians",
    color: "purple",
    icon: "M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944...",
  },
];